package entity;
// Generated Oct 16, 2016 4:41:30 PM by Hibernate Tools 4.3.1



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private String code;
     private String name;
     private Double price;
     private String image;

    public Product() {
    }

	
    public Product(String code) {
        this.code = code;
    }
    public Product(String code, String name, Double price) {
        this.code = code;
        this.name = name;
        this.price = price;
    }
    public Product(String code, String name, Double price, String image) {
       this.code = code;
       this.name = name;
       this.price = price;
       this.image = image;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


